---
development:
  cloud_name: <%= ENV["CLOUDINARY_CLOUD_NAME"] %>
  api_key: <%= ENV["CLOUDINARY_API_KEY"] %>
  api_secret: <%= ENV["CLOUDINARY_API_SECRET"] %>
  enhance_image_tag: <%= ENV["CLOUDINARY_ENHANCE_IMAGE_TAG"] == "true" %>
  static_image_support: <%= ENV["CLOUDINARY_STATIC_IMAGE_SUPPORT"] == "true" %>
production:
  cloud_name: <%= ENV["CLOUDINARY_CLOUD_NAME"] %>
  api_key: <%= ENV["CLOUDINARY_API_KEY"] %>
  api_secret: <%= ENV["CLOUDINARY_API_SECRET"] %>
  enhance_image_tag: <%= ENV["CLOUDINARY_ENHANCE_IMAGE_TAG"] == "true" %>
  static_image_support: <%= ENV["CLOUDINARY_STATIC_IMAGE_SUPPORT"] == "true" %>
test:
  cloud_name: <%= ENV["CLOUDINARY_CLOUD_NAME"] %>
  api_key: <%= ENV["CLOUDINARY_API_KEY"] %>
  api_secret: <%= ENV["CLOUDINARY_API_SECRET"] %>
  enhance_image_tag: <%= ENV["CLOUDINARY_ENHANCE_IMAGE_TAG"] == "true" %>
  static_image_support: <%= ENV["CLOUDINARY_STATIC_IMAGE_SUPPORT"] == "true" %>
