email_regex: !ruby/regexp /\A([\w+\-].?)+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i
minimum_frequency:
  male: 3
  female: 4
default_frequency: 4
statuses:
  can_donate: can_donate
  almost: almost
  cannot_donate: cannot_donate
  unknown: unknown
radiuses:
  1km: 1
  2km: 2
  5km: 5
default_radius: 1
default_position:
  lat: 16.075588999999994
  lng: 108.15342699999997
admin_email: <%= ENV["ADMIN_EMAIL"] %>
cloudinary_default_path: "https://res.cloudinary.com/sontd/image/upload/"
avatar_cloudinary:
  file: "default_avatar_bmsdn.png"
  version: "v1494756572"
image_cloudinary:
  file: "default_article.png"
  version: "v1494760421"
