email_regex: !ruby/regexp /\A([\w+\-].?)+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i
minimum_frequency:
  male: 3
  female: 4
default_frequency: 4
statuses:
  can_donate: can_donate
  almost: almost
  cannot_donate: cannot_donate
  unknown: unknown
radiuses:
  1km: 1
  2km: 2
  5km: 5
default_radius: 1
default_position:
  lat: 16.075588999999994
  lng: 108.15342699999997
